kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind-stage-cluster
networking:
  podSubnet: "10.246.0.0/16"
  serviceSubnet: "10.98.0.0/12"
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30100
    hostPort: 30100
    protocol: TCP
  - containerPort: 30101
    hostPort: 30101
    protocol: TCP