kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind-devops-cluster
networking:
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30080
    hostPort: 30080
    protocol: TCP
  - containerPort: 30443
    hostPort: 30443
    protocol: TCP
  - containerPort: 8080
    hostPort: 8080
    protocol: TCP