name: PR Review Env

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set PR Namespace
        if: github.event.action != 'closed'
        run: echo "NAMESPACE=pr-${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - name: Build Docker image
        if: github.event.action != 'closed'
        run: |
          docker build -t $DOCKERHUB_USERNAME/nodejs-app:pr-${{ github.event.pull_request.number }} .
          echo "IMAGE_TAG=pr-${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - name: Docker login
        if: github.event.action != 'closed'
        run: echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin

      - name: Push Docker image
        if: github.event.action != 'closed'
        run: docker push $DOCKERHUB_USERNAME/nodejs-app:$IMAGE_TAG

      - name: Update Helm Chart
        if: github.event.action != 'closed'
        run: |
          sed -i "s/tag: .*/tag: $IMAGE_TAG/" nodejs-app-chart/values.yaml

      - name: Deploy via ArgoCD ApplicationSet
        if: github.event.action != 'closed'
        uses: argoproj/argocd-action@v2
        with:
          argocd-server: ${{ secrets.ARGOCD_SERVER }}
          username: ${{ secrets.ARGOCD_USERNAME }}
          password: ${{ secrets.ARGOCD_PASSWORD }}
          command: app sync pr-${{ github.event.pull_request.number }}

      - name: Delete PR environment
        if: github.event.action == 'closed'
        uses: argoproj/argocd-action@v2
        with:
          argocd-server: ${{ secrets.ARGOCD_SERVER }}
          username: ${{ secrets.ARGOCD_USERNAME }}
          password: ${{ secrets.ARGOCD_PASSWORD }}
          command: app delete pr-${{ github.event.pull_request.number }}
